{
 "title": "JVM Quarkus - Micrometer Metrics",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(exported_job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{exported_job=\"$application\"},exported_instance)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{exported_job=\"$application\", exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{exported_job=\"$application\", exported_instance=\"$instance\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{exported_job=\"$application\",exported_instance=\"$instance\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{exported_job=\"$application\",exported_instance=\"$instance\", area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Vert.x Worker Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker pool queue size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "worker_pool_queue_size{exported_job=\"$application\"}",
       "legendFormat": "{{label-name}}"
      }
     ]
    },
    {
     "title": "Active workers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 2 },
     "targets": [
      {
       "expr": "worker_pool_active{exported_job=\"$application\"}",
       "legendFormat": "{{label-name}}"
      }
     ]
    },
    {
     "title": "Idle workers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "worker_pool_idle{exported_job=\"$application\"}",
       "legendFormat": "{{label-name}}"
      }
     ]
    }
   ]
  },
  { "title": "Agroal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Available connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "agroal_available_count{exported_job=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 3 },
   "targets": [
    {
     "expr": "agroal_active_count{exported_job=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Awaiting connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 3 },
   "targets": [
    {
     "expr": "agroal_awaiting_count{exported_job=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max used connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "agroal_max_used_count{exported_job=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{exported_job=\"$application\", exported_instance=\"$instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{exported_job=\"$application\", exported_instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\"}[2m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 108 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", exported_instance=\"$instance\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\", status!~\"5..\"}[2m]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{exported_job=\"$application\", exported_instance=\"$instance\", status!~\"5..\"})",
       "legendFormat": "HTTP - MAX"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 108 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\", status=~\"5..\"}[5m]))",
       "legendFormat": "HTTP - 5xx"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 140 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 140 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{exported_job=\"$application\", exported_instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 140 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{exported_job=\"$application\", exported_instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{exported_job=\"$application\", exported_instance=\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 140 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_memory_rss_bytes{exported_job=\"$application\", exported_instance=\"$instance\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_swap_bytes{exported_job=\"$application\", exported_instance=\"$instance\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_rss_bytes{exported_job=\"$application\", exported_instance=\"$instance\"} + process_memory_swap_bytes{exported_job=\"$application\", exported_instance=\"$instance\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 149 },
     "repeat": "jvm_memory_pool_heap",
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 150 },
     "repeat": "jvm_memory_pool_nonheap",
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\"}[2m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 151 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{exported_job=\"$application\", exported_instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{exported_job=\"$application\", exported_instance=\"$instance\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 151 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{exported_job=\"$application\", exported_instance=\"$instance\"}[2m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{exported_job=\"$application\", exported_instance=\"$instance\"}[2m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 152 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{exported_job=\"$application\", exported_instance=\"$instance\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 152 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{exported_job=\"$application\",exported_instance=\"$instance\"}[2m])",
       "legendFormat": "delta-1m"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 153 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 153 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{exported_job=\"$application\", exported_instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 153 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{exported_job=\"$application\", exported_instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 153 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{exported_job=\"$application\", exported_instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Edpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\"}[2m])",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Average inbound request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{exported_job=\"$application\", exported_instance=\"$instance\"}[4m]) / rate(http_server_requests_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\"}[4m])",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Maximum inbound request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{exported_job=\"$application\", exported_instance=\"$instance\"}",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Sum of the duration of every request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{exported_job=\"$application\", exported_instance=\"$instance\"}[2m])",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GraphQL requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of GraphQL requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\"}[2m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    },
    {
     "title": "Average inbound request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_sum{exported_job=\"$application\", exported_instance=\"$instance\"}[4m]) / rate(mp_graphql_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\"}[4m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    },
    {
     "title": "Maximum inbound GraphQL request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mp_graphql_seconds_max{exported_job=\"$application\", exported_instance=\"$instance\"}",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    },
    {
     "title": "Sum of the duration of every GraphQL request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_sum{exported_job=\"$application\", exported_instance=\"$instance\"}[2m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    }
   ]
  }
 ]
}