receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  # Data sources: metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: todolist-kogito-app-service-pgsql-1
          metrics_path: '/q/metrics/prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: [todolist-kogito-app-service-pgsql-1:8080]
       # - job_name: todolist-kogito-app-service-kafka-1
       #   metrics_path: '/q/metrics/prometheus'
       #   scrape_interval: 5s
       #   static_configs:
       #     - targets: [todolist-kogito-app-service-kafka-1:8080]
       # - job_name: todolist-kogito-app-service-elastic-1
       #   metrics_path: '/q/metrics/prometheus'
       #   scrape_interval: 5s
       #   static_configs:
       #     - targets: [todolist-kogito-app-service-elastic-1:8080]
exporters:
  # OTLP
  #otlp:
    #endpoint: otelcol:4317
  # Data sources: traces
  otlp/jaeger:
    endpoint: "http://todolist-jaeger:4317"
    tls:
      insecure: true
  elasticsearch:
    endpoints: [http://todolist-elasticsearch:9200]
    user: elastic
    password: 
    api_key:
  prometheus:
    endpoint: 0.0.0.0:8889
  prometheusremotewrite:
    endpoint: http://localhost:9090/api/v1/write
    tls:
      insecure: true
  debug:
    verbosity: detailed

processors:
  batch:

service:
  telemetry:
    logs:
      level: WARN
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      #exporters: [otlp/jaeger,elasticsearch]
      exporters: [otlp/jaeger]
      #exporters: [spanmetrics, otlp]
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics:
      receivers: [otlp,prometheus]
    #  processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      #exporters: [debug,elasticsearch]
      exporters: [debug]
    #metrics/spanmetrics:
    #    receivers: [spanmetrics]
    #    exporters: [prometheus]
  
